---
# tasks file for K8S-Master

- name: "Installing Docker"
  package:
          name: docker
          state: present

- name: "Start Docker Service with permanently enable"
  service:
          name: docker
          state: started
          enabled: yes

- name: "Configured Yum Repo for K8S"
  blockinfile:
    create: yes  
    path: /etc/yum.repos.d/kubernetes.repo
    block: |
            [kubernetes]
            name=Kubernetes
            baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
            enabled=1
            gpgcheck=1
            repo_gpgcheck=1
            gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
            exclude=kubelet kubeadm kubectl

- name: "Installing kubelet,kubeadm,kubectl"
  shell: yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
  changed_when: false

- name: "Start kubelet service with permanently enable"
  service:
          name: kubelet
          state: started
          enabled: yes

- name: "Pulling all config images"
  command: kubeadm config  images pull
  changed_when: false

- name: "Changing CGROUP Driver"
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"]
      }
  changed_when: false

- name: "Restart Docker Service"
  service:
          name: docker
          state: restarted

- name: "Install ip-route-c"
  package:
          name: iproute-tc
          state: present

- name: "Set IP Tables"
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
  changed_when: false

- name: "Starting sysctl"
  shell: sysctl --system
  changed_when: false

- name: "Initializing kubeadm"
  shell: kubeadm init --pod-network-cidr=10.240.0.0/16  --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem
  changed_when: false
- name: "Creating .kube Directory"
  file:
    path: $HOME/.kube
    state: directory
  changed_when: false

- name: "Copying Config File of K8S Master"
  command: cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  changed_when: false

- name: "Changing Ownership of K8S Config File"
  shell: chown $(id -u):$(id -g) $HOME/.kube/config
  changed_when: false

- name: "Configuring Flannel CNI for K8S Master"
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  changed_when: false

- name: "Generating Token"
  shell: kubeadm token  create  --print-join-command
  register: token
  ignore_errors: yes

- debug: 
    var: token.stdout_lines
